### ISSUE TITLE
What does each dimension of data represent？

### ISSUE THREAD

**Issue by aanxud888** [TheDatumOrg/kshape-python#18]
Hello， in the demo that in MTS clustering, that is "multivariate_ts_datasets = np.random.rand(200, 60, 6)". What is the 60,6 represents?60 is the sequence length? 6 is feature number?

**Comment by firmai** [comment]
Strange that this is left unanswered

**Comment by HaojunLi** [comment]
Hi,
In the provided example, multivariate_ts_datasets = np.random.rand(200, 60, 6), 200 represents the number of time series, 60 represents the length of a time series and 6 is the time series channels. Thank you.
Best,
Haojun
