### ISSUE TITLE
_LinAlgError: linalg.eigh: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 994).

### ISSUE THREAD

**Issue by holydick99** [TheDatumOrg/kshape-python#19]
after run my dataset there are sth worng, and i can't find the solution on the internet. So sad
![BI5AYHK~ 7JDNR563JHG)VC](https://github.com/user-attachments/assets/57e4db45-35ed-4890-b2dd-deb8369ba2ad)
![XF1~(5X{1)URY}(3 8%T`ZR](https://github.com/user-attachments/assets/5456254e-5373-4a60-aa25-708216b8f649)
![29BK@7D _RBE504{RL2_REN](https://github.com/user-attachments/assets/40c9e3c1-2a65-4e4a-82b2-ae2754ef1ba4)

**Comment by minD9it** [comment]
I have a same issue, did you solve it??

**Comment by holydick99** [comment]
> I have a same issue, did you solve it??

the problem is there are too many 0 or 1 in my arrary, after i get mean in different channel it can run

**Comment by minD9it** [comment]
> > I have a same issue, did you solve it??
> 
> the problem is there are too many 0 or 1 in my arrary, after i get mean in different channel it can run

Was there any problem with the function 'zscore'??  I think my problem is in zscore function,

```py
def zscore(a, axis=0, ddof=0):
    mns = a.mean(dim=axis)
    sstd = a.std(dim=axis, unbiased=(ddof == 1))
    if axis and mns.dim() < a.dim():
        x=(a - mns.unsqueeze(axis)).div(sstd.unsqueeze(axis)) #  **<<after this code 1**
        return x.masked_fill(torch.isnan(x), 0) # nan -> 0
        #return torch.nan_to_num((a - mns.unsqueeze(axis)).div(sstd.unsqueeze(axis)))
    else:
        x=a.sub_(mns).div(sstd) #  **<<after this code 2**
        return x.masked_fill(torch.isnan(x), 0) # nan -> 0
        #return torch.nan_to_num(a.sub_(mns).div(sstd))
```
after these code, variable _x_ contains 'inf' or '-inf'. It causes the error :(

I can't find out solution about it...

**Comment by holydick99** [comment]
It's seems without any ERROR. I only can give you my view, the problem you are facing is likely due to division by zero or you fill too many 0 in your data, you can try replace NAN by mean. I'm just year 2 student of university so maybe my solutions are not so correctly
