### ISSUE TITLE
Default Z-score axis

### ISSUE THREAD

**Issue by adamgayoso** [TheDatumOrg/kshape-python#3]
Shouldn't the default be 1? This is how the paper describes the z-normalization.

**Comment by Mic92** [comment]
python is zero-indexed, while the authors used matlab where indices begin at 1.

**Comment by adamgayoso** [comment]
I was more talking about zscoring the raw time series, you would probably zscore each time series, not each time point

**Comment by Mic92** [comment]
Indeed, the example code was wrong.
