### ISSUE TITLE
peaks in ram usage

### ISSUE THREAD

**Issue by tolgamalachi** [TheDatumOrg/kshape-python#7]
hello guys,

you should definetley check your code against the k-shape implementation from tslearn.
your code has very high peaks in ram usage for k > 4; m = 56; n = 5,000,000.
(n is the number of time series, k is the number of clusters, and m is the length of the time series; from the original paper)
It goes up to 196 gigabyte of ram usage. The tslearn-implementation only uses up to 7 gigabyte (like your implementation) but it does not have the peaks. Your solution builds up a peak and then goes down rapidly.

at least put a link to the tslearn project in your readme-file.
https://github.com/rtavenar/tslearn/blob/master/tslearn/clustering.py#L597

thanks for your implementation though. At least you tried and open sourced it. Thanks for that =)

**Comment by johnpaparrizos** [comment]
Thanks for pointing this out. We believe this issue got resolved with our recent update.
