### ISSUE TITLE
k-shape with multi-dimensional time-series

### ISSUE THREAD

**Issue by miguelvr** [TheDatumOrg/kshape-python#9]
Is it possible to cluster sequences with more than one dimension? 

i.e. a tensor of shape `(n_samples, seq_length, n_features)` as opposed to just `(n_samples, seq_length)`

**Comment by Mic92** [comment]
I have no idea if the algorithm can do this. Not in the current implementation. It is better to ask the author itself: https://github.com/Mic92/kshape#original-paper

**Comment by miguelvr** [comment]
thanks!

**Comment by denalist** [comment]
@miguelvr  Hi I'm trying to use K-shape to cluster sequences, like (n_samples, seq_length, n_features), I wonder if K shaped worked for you ? 
thanks in advance!
